model_type: gafl

flexibility:
  outputs:
    - global_rmsf
    - local_flex
  out_dims:
    - 1
    - 1
  max_values:
    - 20.
    - 5.

node_embed_size: 32
edge_embed_size: 16
symmetric: False
node_features:
  c_s: ${model.node_embed_size}
  c_pos_emb: 64
  embed_diffuse_mask: False
  max_num_res: 2000
  embed_aatype: False
  aatype_embed_size: 64
  embed_breaks: False
  embed_res_idx: False
edge_features:
  single_bias_transition_n: 2
  c_s: ${model.node_embed_size}
  c_p: ${model.edge_embed_size}
  relpos_k: 64
  use_rbf: True
  num_rbf: 32
  feat_dim: 32
  num_bins: 22
  embed_breaks: False
  embed_res_idx: True
gfa:
  c_s: ${model.node_embed_size}
  c_z: ${model.edge_embed_size}
  c_hidden: 32
  no_heads: 4
  no_qk_points: 4
  no_v_points: 4
  body_order: 3
  seq_tfmr_num_heads: 4
  seq_tfmr_num_layers: 1
  num_blocks: 2
  readout_c_hidden: 16